# action.yml
name: 'Maven Dependencies Action'
description: 'Builds a Maven project from a Github Repository'
inputs:
  repository:
    description: 'The Github Repository to build'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
